### ISSUE TITLE
Support "Display root categories not as headings"

### ISSUE THREAD

**Issue by frdmn** [hgtonight/Plugin-ExpandableCategories#1]
Looks like this at the moment:

![bildschirmfoto 2014-07-04 um 08 43 58](https://cloud.githubusercontent.com/assets/944459/3478866/9cf4b62e-0346-11e4-9a55-f5dc0cb742bd.png)

**Comment by hgtonight** [comment]
Hi!

What theme is that?

**Comment by frdmn** [comment]
[Bootstrap](http://vanillaforums.org/addon/bootstrap-theme) by @kasperisager

**Comment by kasperisager** [comment]
This is theme-specific as Bootstrap for Vanilla styles the anchors (`<a>`) of the panels rather than the list items (`<li>`).

**Comment by hgtonight** [comment]
As Kasper noted, this is a theme conflict. I won't be changing the core code to support it.

That said, here are some CSS rules that look decent/work on Bootstrap:

```
/* Root categories with sub categories hidden*/
ul.PanelCategories li.Leader a, ul.PanelCategories li.Leader.Active a {
    padding-left: 20px;
    background-image: url('arrow.png');
    background-repeat: no-repeat;
    background-position: 8px center;
}

/* Root categories with sub categories expanded */
ul.PanelCategories li.Leader.Expanded a, ul.PanelCategories li.Leader.Active.Expanded a {
    background-image: url('arrow-down.png');
    background-repeat: no-repeat;
    background-position: 6px center;
}

/* This makes it feel a little more polished */
ul.PanelCategories li.Heading {
    cursor: default;
}
```

**Comment by hgtonight** [comment]
Thanks for the feedback!

**Comment by frdmn** [comment]
@hgtonight @kasperisager thank you guys! works like a charm! :)
